# Site settings
title: HyoungJong's PotoFolio
description: 포토폴리오~
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://wkgmr1111.github.io/wkgmr1111.github.io-medc1/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 이 형 종
# user_description: 

# user_title: Software Developer
email: 'wkgmr1111@gmail.com'
twitter_username: lorem_ipsum
github_username:  "https://github.com/wkgmr1111/SelfGuideBook"
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

